<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start Shopping</name>
   <tag></tag>
   <elementGuidId>60fa240d-79e4-4a4e-8118-2343e39b3659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='start-shopping-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#start-shopping-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b2addba-b234-49bb-88c1-bbc79b08f536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-semibold rounded-md shadow-md p-2 transition ease-out duration-500 transform hover:-translate-y-0.5  hover:scale-110 hover:opacity-80 whitespace-nowrap bg-secondary text-white p-4 leading-4</value>
      <webElementGuid>4c1fc4d9-f0e9-4d99-8255-0f47d6ec78dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start-shopping-button</value>
      <webElementGuid>ec3c3e76-edff-4fa2-9b5b-f158d6cf10f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f93862a-3c4c-4062-9ceb-4f633c3b7e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Shopping →</value>
      <webElementGuid>ad14de21-fa99-4ff8-93d6-099ffef692ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-shopping-button&quot;)</value>
      <webElementGuid>aed2b8bc-1196-4f46-84ee-d7d50545472e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='start-shopping-button']</value>
      <webElementGuid>38c090df-c99b-4cba-90e9-2f5126872005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/div[2]/button</value>
      <webElementGuid>47d1ad58-9b7e-4e4f-b70b-302bacdd7a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::button[4]</value>
      <webElementGuid>07b8e883-a9ba-46fb-9e5d-4970f2a81e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>d9ec97d7-ff63-4027-81ff-e691770bc842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'start-shopping-button' and @type = 'button' and (text() = 'Start Shopping →' or . = 'Start Shopping →')]</value>
      <webElementGuid>01b2e461-b242-4c04-b1a0-6a6e3f51c7fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
