<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_remove_item1</name>
   <tag></tag>
   <elementGuidId>809880a2-b8a9-4635-a73e-ff4751231f29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cart-items']/tbody/tr/td/div/span/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4037ed0a-87fc-44a2-bdcc-b6e5cb707a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locator</name>
      <type>Main</type>
      <value>remove-from-cart-button</value>
      <webElementGuid>c8bda358-61cf-41bb-b8ab-283f1101839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a8071e9-785c-4ac5-9185-facda0a6acfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove one Piggybank from cart</value>
      <webElementGuid>c02b685e-a004-48b1-8765-1fb5774093da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125 </value>
      <webElementGuid>53c02b58-8e5d-4db2-8cbb-91d431527a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove one Piggybank from cart</value>
      <webElementGuid>621a9cf7-b9e3-44b3-95b3-78afc244535d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/minus-circle-neutral.10895ea6.svg</value>
      <webElementGuid>a008cdfd-cd27-4866-99c8-d0daa6aae60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>bde8eda4-cbf2-4e6c-bbc6-c3eb44f167d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-items&quot;)/tbody[1]/tr[1]/td[@class=&quot;px-2 py-1 md:px-6 md:py-3 text-left lg:text-lg&quot;]/div[@class=&quot;grid place-content-center&quot;]/span[@class=&quot;h-auto&quot;]/div[@class=&quot;flex place-items-center text-sm&quot;]/img[@class=&quot;align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125&quot;]</value>
      <webElementGuid>6b34e4db-0d7c-4862-a4e4-d9bab2722f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cart-items']/tbody/tr/td/div/span/div/img</value>
      <webElementGuid>d4a825d1-8fe9-41d3-a1d3-387ec9be0804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='-']</value>
      <webElementGuid>61f70f7a-b581-4008-9f0c-9924f39006e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>3f48139e-de89-482b-afa9-56b4fb0dbe4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Remove one Piggybank from cart' and @src = '/static/media/minus-circle-neutral.10895ea6.svg' and @alt = '-']</value>
      <webElementGuid>df4f11dd-ae34-4191-a394-d9d928743b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
