<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_add_BathToys</name>
   <tag></tag>
   <elementGuidId>d84f74b7-c212-4e93-9d81-0d6e1f694c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div[3]/div[2]/div/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4ae9dea-96d2-41f8-9450-5c1aebfc9e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locator</name>
      <type>Main</type>
      <value>add-to-cart-button</value>
      <webElementGuid>ec6041a5-cedd-4157-adee-2901e0b7b216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39e9f0fe-4038-48eb-bb27-735345630edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add one Bath Toys to cart</value>
      <webElementGuid>95a904bf-afbc-4ea8-9133-d2437b75e7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125 </value>
      <webElementGuid>bf510c0d-bee7-47c3-87db-808a4a2a1a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add one Bath Toys to cart</value>
      <webElementGuid>41cd2e46-4993-4310-bbf5-50f33915702b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/plus-circle-neutral.6ccef301.svg</value>
      <webElementGuid>a31e79af-fcfa-432b-81f4-d530a8d8c857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>b8b25578-5a4a-48fb-abe4-dace8ea866a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;my-7&quot;]/div[@class=&quot;grid grid-cols-3 mx-auto max-w-4xl text-base font-medium leading-6&quot;]/div[@class=&quot;relative flex flex-col p-4 m-4 rounded-md border border-gray-200 align-middle bg-white 
      transition duration-300 ease-in-out border-4 hover:shadow-lg hover:border-accent
      transform hover:-translate-y-0.5 hover:scale-102&quot;]/div[@class=&quot;mt-1 justify-between flex&quot;]/div[@class=&quot;flex place-items-center text-sm&quot;]/img[@class=&quot;align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125&quot;]</value>
      <webElementGuid>e05bdb43-130e-4d96-bf44-d52fa370d05c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[3]/div[2]/div/div[2]/div[2]/img</value>
      <webElementGuid>00b64d04-9ed7-401e-9488-a8d9edf91dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='+']</value>
      <webElementGuid>08763faf-3ed6-40b2-96cc-34b92d8570d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>a4a8e91b-539f-410d-b718-42b3b6072009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Add one Bath Toys to cart' and @src = '/static/media/plus-circle-neutral.6ccef301.svg' and @alt = '+']</value>
      <webElementGuid>68b80847-1838-4186-8a59-de9bf106118a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
