<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_searchButton</name>
   <tag></tag>
   <elementGuidId>2f61e012-417e-4e89-8a9c-eefe5ac33760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search-button']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.text-gray-600.h-4.w-4.fill-current</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b547a4ec-40ce-48ed-a45c-afe56ee1eb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-600 h-4 w-4 fill-current</value>
      <webElementGuid>a34b045d-c4e3-4c70-811b-c9e56c17fad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/search.61329981.svg</value>
      <webElementGuid>d0fd6ffe-1e5e-4797-859e-5956032c2bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>c57eab33-94aa-4a58-b628-bedfd06e9b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search for products</value>
      <webElementGuid>2dd55605-dc77-4b3b-bafc-c07a75031882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-button&quot;)/img[@class=&quot;text-gray-600 h-4 w-4 fill-current&quot;]</value>
      <webElementGuid>1bc918c8-07c1-498e-9b6c-f1c5f59c5d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='search-button']/img</value>
      <webElementGuid>a53843ad-9fa9-48fd-a2ed-00756ea66281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Search']</value>
      <webElementGuid>8e4b294a-5d3e-4b5b-bfcf-cc9810f22d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>b9126387-688d-4f2c-9f2d-03b7f5dba7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/search.61329981.svg' and @alt = 'Search' and @title = 'Search for products']</value>
      <webElementGuid>415974d7-fab2-4681-a5a5-91a8d2cef4a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
