<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_add_PiggyBank</name>
   <tag></tag>
   <elementGuidId>2b6f8e1c-78f4-4d58-95ea-153e5df59e81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div[3]/div/div[3]/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5e8b203d-19e2-41db-b03f-5421df236673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locator</name>
      <type>Main</type>
      <value>add-to-cart-button</value>
      <webElementGuid>3e242377-3555-4639-9d30-39fbc5eb1256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7045252d-6a57-48f2-a94c-3f4a6f25cc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add one Piggybank to cart</value>
      <webElementGuid>665ae754-3139-4e9f-a347-f18d1afabe30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125 </value>
      <webElementGuid>b6f98e40-9114-4c06-8c50-9bfcbb42757a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add one Piggybank to cart</value>
      <webElementGuid>c781a6ff-2743-4ea3-bcd2-3b745189bde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/plus-circle-neutral.6ccef301.svg</value>
      <webElementGuid>9b03073d-139a-4b39-8d51-836d4e879e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>62df1a9d-3731-4139-b5c2-baf6b118e903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;my-7&quot;]/div[@class=&quot;grid grid-cols-3 mx-auto max-w-4xl text-base font-medium leading-6&quot;]/div[@class=&quot;relative flex flex-col p-4 m-4 rounded-md border border-gray-200 align-middle bg-white 
      transition duration-300 ease-in-out border-4 hover:shadow-lg hover:border-accent
      transform hover:-translate-y-0.5 hover:scale-102&quot;]/div[@class=&quot;mt-1 justify-between flex&quot;]/div[@class=&quot;flex place-items-center text-sm&quot;]/img[@class=&quot;align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125&quot;]</value>
      <webElementGuid>49467092-7c24-4dc3-b60b-11fd515f2ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[3]/div/div[3]/div[2]/div[2]/img</value>
      <webElementGuid>e27c7644-060c-4c8b-9cbd-c8171a445ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='+'])[3]</value>
      <webElementGuid>e66f4160-f0a8-44e3-ad96-8c7786dd324a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/img</value>
      <webElementGuid>4518087b-be75-402d-9eb4-9b41426a139b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Add one Piggybank to cart' and @src = '/static/media/plus-circle-neutral.6ccef301.svg' and @alt = '+']</value>
      <webElementGuid>00b84057-4aea-461f-b088-a4155487331f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
