<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_remove_item2</name>
   <tag></tag>
   <elementGuidId>ebb0389a-fdba-4d1c-b556-05bdff4d9063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cart-items']/tbody/tr/td/div/span/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>98403c0b-d237-4808-9622-1ad642b355bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locator</name>
      <type>Main</type>
      <value>remove-from-cart-button</value>
      <webElementGuid>de8f9304-565f-42bd-a53d-c87dc7774077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f5a6890-5b6c-44a9-8e8b-771599437850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove one Bath Toys from cart</value>
      <webElementGuid>211d6b26-910a-435b-ac29-f84d689a36f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125 </value>
      <webElementGuid>8a50f21b-44b7-43a7-82f2-ae1a04e329fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove one Bath Toys from cart</value>
      <webElementGuid>9aadf95f-2401-4238-91ea-c94f2b7080d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/minus-circle-neutral.10895ea6.svg</value>
      <webElementGuid>3b15790e-b280-4c09-9de7-4034ed66225a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>2158cf76-4767-4f7f-b6f4-cbfa7214d59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-items&quot;)/tbody[1]/tr[1]/td[@class=&quot;px-2 py-1 md:px-6 md:py-3 text-left lg:text-lg&quot;]/div[@class=&quot;grid place-content-center&quot;]/span[@class=&quot;h-auto&quot;]/div[@class=&quot;flex place-items-center text-sm&quot;]/img[@class=&quot;align-middle m-auto w-5 transition duration-200 cursor-pointer transform ease-in-out hover:scale-125&quot;]</value>
      <webElementGuid>837149a7-d123-4364-bfed-d10957d1a9b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cart-items']/tbody/tr/td/div/span/div/img</value>
      <webElementGuid>721ea6f0-98ff-4124-b910-595c0f27731c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='-']</value>
      <webElementGuid>dd5693a6-62fd-474b-b777-7c67b93767dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>82f6c1b5-c882-4894-8148-dc5c066004df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Remove one Bath Toys from cart' and @src = '/static/media/minus-circle-neutral.10895ea6.svg' and @alt = '-']</value>
      <webElementGuid>1a7d6ae6-3e88-4ad3-9f94-541c0d9b1e64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
