<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Are you sure that you want to logoutCancelYes</name>
   <tag></tag>
   <elementGuidId>c29f4e2f-0aca-4836-9ba3-3aa3921560d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logout-modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logout-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>912af834-ca43-4282-ac38-2f666f2875ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logout-modal</value>
      <webElementGuid>f0936a1d-ce4a-4976-8a0e-ab6abd6dbd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReactModal__Content ReactModal__Content--after-open absolute top-1/3 left-1/2 transform -translate-x-1/2 -translate-y-1/2 max-w-2xl m-auto w-2/5 border border-gray-400 rounded-md pt-10 p-8 bg-gray-50</value>
      <webElementGuid>4739bdeb-afaa-4f6c-a7f3-6b23d9f5dc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b3d726f3-12a8-4a34-80f8-cd4bc5ecd93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>c21fc43e-7075-404b-bb20-90b328435b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98ed66bb-f4b3-4021-9059-5e032aaccb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>logout-modal-heading</value>
      <webElementGuid>6d6a7ee9-b26a-44ce-b977-7c091c84372e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>logout-modal-body</value>
      <webElementGuid>01366dd5-3a6b-481b-b047-f7d81dc6d4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you sure that you want to logout?CancelYes</value>
      <webElementGuid>6ef06247-e3cc-42c2-b61a-451ce246a7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logout-modal&quot;)</value>
      <webElementGuid>59a53163-6437-441e-af0b-b29cc24c7110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='logout-modal']</value>
      <webElementGuid>b8a6e642-36eb-40f7-bdc5-2e2b37a7dc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe now to get updates on promotions and coupons.'])[1]/following::div[7]</value>
      <webElementGuid>7e9dae9c-c6a5-41b4-a997-d473ae9f753e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Us'])[1]/following::div[7]</value>
      <webElementGuid>666f457e-d168-4862-bc49-7e764d3fe5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>498b455e-2df4-4bd5-95d8-0606a8f488a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'logout-modal' and (text() = 'Are you sure that you want to logout?CancelYes' or . = 'Are you sure that you want to logout?CancelYes')]</value>
      <webElementGuid>d9eae498-24bd-481a-928b-7254a241304f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
