<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log InUsernamePasswordI agree to the terms of serviceCancelLog In</name>
   <tag></tag>
   <elementGuidId>82ddcca3-7ecd-43a5-be6c-3d862b83ea36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dddc6539-3059-4ff2-96c6-8e44e3bc19bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-modal</value>
      <webElementGuid>5bd10fde-f6c1-4031-86ce-181a4f7e0acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReactModal__Content ReactModal__Content--after-open absolute top-1/3 left-1/2 transform -translate-x-1/2 -translate-y-1/2 max-w-2xl m-auto w-2/5 border border-gray-400 rounded-md pt-10 p-8 bg-gray-50</value>
      <webElementGuid>31111600-1543-45b0-9d38-93db383c3ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1cbe55aa-0d9e-41a0-9c57-c792b42eeb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>db148ab8-6454-4cd7-8fdc-a2c6759fb32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8cafac7c-df39-4e33-8756-5207eecac008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>login-modal-heading</value>
      <webElementGuid>e1afd836-1672-41e1-b988-0b73cbdc9fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>login-modal-body</value>
      <webElementGuid>1ae69278-0b17-424d-aff0-f6f721165a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log InUsername*Password*I agree to the terms of serviceCancelLog In</value>
      <webElementGuid>332be5f3-3f28-4ca0-a816-2cbe0b820dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-modal&quot;)</value>
      <webElementGuid>fe53d6b5-cb4a-4579-8009-c6d038778011</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login-modal']</value>
      <webElementGuid>f26c6928-1f37-430b-8bfd-9005d608af0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe now to get updates on promotions and coupons.'])[1]/following::div[6]</value>
      <webElementGuid>0f5b243e-157b-4672-9078-6e3bfc6890da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Us'])[1]/following::div[6]</value>
      <webElementGuid>e1eda9cb-3fa6-45a1-ab74-c8cc371853fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>928e7c56-2224-47f4-8a91-83e2074fbbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login-modal' and (text() = 'Log InUsername*Password*I agree to the terms of serviceCancelLog In' or . = 'Log InUsername*Password*I agree to the terms of serviceCancelLog In')]</value>
      <webElementGuid>27e0f813-d120-4e12-9c9a-805b25d21e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
